- name: create jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://jenkins.nvrnagella.online:8080
    password: "{{jenkins_password}}"
    user: admin
  loop: "{{folders}}"


- name: create multibranch pipeline job
  ansible.builtin.include_tasks:
    file: mbranchpipeline.yml
  loop: "{{ci_pipelines}}"

- name: create single branch pipeline job
  ansible.builtin.include_tasks:
    file: s-pipeline.yml
  loop: "{{pipelines}}"


