- name: create jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item}}"
    url: http://localhost:8080
    password: "{{jenkins_password}}"
    user: admin
  loop:
    - CIPipelines

- name: including job creation task
  ansible.builtin.include_tasks:
    file: pipeline.yml
  loop:
    - frontend
    - catalogue
    - cart

