- name: create jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.1.250:8080
    password: "{{jenkins_password}}"
    user: admin
  loop:
    - CIPipelines

- name: including job creation task
  ansible.builtin.include_tasks:
    file: s-pipeline.yml
  loop:
    - {name: "frontend", dir: "CIPipelines"}
    - {name: "catalogue", dir: "CIPipelines"}
    - {name: "cart", dir: "CIPipelines"}
    - {name: "shipping", dir: "CIPipelines"}
    - {name: "payment", dir: "CIPipelines"}
    - {name: "user", dir: "CIPipelines"}

