- name: copy job config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/job.xml') }}"
    name: "{{item}}"
    url: http://172.31.89.234:8080
    password: "{{jenkins_password}}"
    username: admin
  loop:
    - frontend
    - catalogue
    - cart

