- name: create jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.2.94:8080
    password: "{{jenkins_password}}"
    user: admin
  loop:


- name: including job creation task
  ansible.builtin.include_tasks:
    file: mbranchpipeline.yml
  loop:


