- name: check if job exists or not
  community.general.jenkins_job_info:
    url: http://jenkins.nvrnagella.online:8080
    user: admin
    password: "{{jenkins_password}}"
    name: "{{item.dir}}/{{item.name}}"
  register: out
  ignore_errors: yes

- name: copy job config file - {{item.dir}}/{{item.name}}
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)
  when: out.failed | bool

- name: create jenkins jobs - {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://jenkins.nvrnagella.online:8080
    password: "{{jenkins_password}}"
    user: admin
  when: out.failed | bool