- name: copy job config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.2.94:8080
    password: "{{jenkins_password}}"
    user: admin