- name: copy job config file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjob.xml') }}"
    name: "{{item}}"
    url: http://localhost:8080
    password: "{{jenkins_password}}"
    user: admin