- name: check if job exists or not
  community.general.jenkins_job_info:
    url: http://jenkins.nvrnagella.online:8080
    user: admin
    password: "{{jenkins_password}}"
    name: "{{item.dir}}/{{item.name}}"
  register: out
  ignore_errors: yes

- name: debug
  debug:
    msg: "{{out}}"

- name: copy job config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://jenkins.nvrnagella.online:8080
    password: "{{jenkins_password}}"
    user: admin