- name: copy job config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.13.144:8080
    password: "{{jenkins_password}}"
    user: admin