- name: check if job exists or not - {{item.dir}}/{{item.name}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://jenkins.nvrnagella.online:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: copy job config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  when: out.rc == 3

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://jenkins.nvrnagella.online:8080
    password: "{{jenkins_password}}"
    user: admin
  when: out.rc == 3